// Package codegen exports the design as code: from the document (scene graph +
// flows) to a project that opens in the browser and that the e2e tests
// generated by internal/flow can drive.
//
// Pipeline, a SINGLE implementation for CLI, MCP and RPC:
//
//	Document -> screens -> IR (ir.go, build.go) -> renderer (html.go | react.go)
//
// The IR is a tree of elements with CSS properties in order; the two renderers
// read the same tree and write CSS in a <style> (html target) or Tailwind
// classes (react target, tailwind.go), so the two outputs cannot diverge. The
// output is DETERMINISTIC: every map in the document is read in an explicit
// order, and the same document produces the same bytes (golden files, PR
// diffs).
//
// The drawing semantics are those of the editor's CANVAS
// (web/src/renderer/canvasRenderer.ts), not those of a "typical" editor: only
// the first fill, the first shadow and the first blur, opacity not inherited
// by children, a frame without a fill is transparent and a shape without a
// fill is grey. Where CSS cannot say the same thing, the comment at that spot
// explains it and docs/codegen.md lists it.
package codegen

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	opendesignerv1 "github.com/bernardoforcillo/opendesigner/gen/opendesigner/v1"
	"github.com/bernardoforcillo/opendesigner/internal/core"
	"github.com/bernardoforcillo/opendesigner/internal/flow"
	"google.golang.org/protobuf/proto"
)

// Target of the generated code.
type Target string

const (
	// TargetHTML: one self-contained HTML file per screen (CSS in <style>,
	// navigation with <a href>).
	TargetHTML Target = "html"
	// TargetReact: Vite + React + TypeScript + Tailwind v4 +
	// react-router-dom project, with the flows' Playwright tests.
	TargetReact Target = "react"
)

// Options configures generation.
type Options struct {
	// Target: html or react (default react).
	Target Target
	// FlowID limits the wiring (and the tests) to one flow; empty = all.
	FlowID string
}

// AssetSource provides the bytes of the document's images by hash. It may be
// nil: images become placeholders.
type AssetSource interface {
	Asset(hash string) ([]byte, error)
}

// File is a generated file; Path is relative to the output root, with "/".
type File struct {
	Path    string
	Content []byte
}

// Output is the set of files, sorted by path.
type Output struct {
	Files []File
	// Warnings: things the generator had to approximate or omit
	// (missing assets, orphan instances, transitions to non-exported nodes).
	Warnings []string
}

// Generate exports `doc`. It does not modify the document.
func Generate(doc *opendesignerv1.Document, opts Options, assets AssetSource) (*Output, error) {
	if doc == nil {
		return nil, errors.New("missing document")
	}
	if opts.Target == "" {
		opts.Target = TargetReact
	}
	if opts.Target != TargetHTML && opts.Target != TargetReact {
		return nil, fmt.Errorf("unknown target %q: use %q or %q", opts.Target, TargetReact, TargetHTML)
	}
	if opts.FlowID != "" {
		if _, ok := doc.GetFlows()[opts.FlowID]; !ok {
			return nil, fmt.Errorf("flow %q not found in the document", opts.FlowID)
		}
	}
	// We work on a COPY: the default route of the screens is written into the
	// meta (flow.PlaywrightTests needs it, it reads `code.route`) without touching
	// the caller's document.
	d := proto.Clone(doc).(*opendesignerv1.Document)

	out := &Output{}
	screens := collectScreens(d, opts.FlowID, &out.Warnings)
	if len(screens) == 0 {
		return nil, errors.New("the document has no screens to export: top-level frames on a page are required")
	}
	assignNames(d, screens, opts)

	files := map[string][]byte{}
	b := &builder{doc: d, assets: assets, files: files, warnings: &out.Warnings}
	switch opts.Target {
	case TargetHTML:
		b.fileDir, b.urlPrefix = "assets/", "assets/"
	default:
		b.fileDir, b.urlPrefix = "public/assets/", "/assets/"
	}
	wireFlows(d, screens, opts, b, &out.Warnings)

	switch opts.Target {
	case TargetHTML:
		renderHTML(d, screens, opts, files)
	default:
		if err := renderReact(d, screens, opts, files, &out.Warnings); err != nil {
			return nil, err
		}
	}

	paths := make([]string, 0, len(files))
	for p := range files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		out.Files = append(out.Files, File{Path: p, Content: files[p]})
	}
	sort.Strings(out.Warnings)
	return out, nil
}

// selectedFlows: the ids of the flows to wire, sorted.
func selectedFlows(d *opendesignerv1.Document, flowID string) []string {
	if flowID != "" {
		return []string{flowID}
	}
	ids := make([]string, 0, len(d.GetFlows()))
	for id := range d.GetFlows() {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// flowTransitions: the transitions of the chosen flows, sorted by id.
func flowTransitions(d *opendesignerv1.Document, flows []string) []*opendesignerv1.Transition {
	in := map[string]bool{}
	for _, f := range flows {
		in[f] = true
	}
	var ts []*opendesignerv1.Transition
	for _, t := range d.GetTransitions() {
		if in[t.GetFlowId()] {
			ts = append(ts, t)
		}
	}
	sort.Slice(ts, func(i, j int) bool { return ts[i].GetId() < ts[j].GetId() })
	return ts
}

// collectScreens: the screens are the top-level children of the pages that
// are FRAMES (component masters, which are frames too, stay out: they are
// pieces to instantiate, not pages) plus any top-level node that a chosen flow
// references. The order is the document's: pages, then order_key.
func collectScreens(d *opendesignerv1.Document, flowID string, warnings *[]string) []*Screen {
	masters := map[string]bool{}
	for _, c := range d.GetComponents() {
		masters[c.GetRootNodeId()] = true
	}
	referenced := map[string]bool{}
	flows := selectedFlows(d, flowID)
	for _, f := range flows {
		if s := d.GetFlows()[f].GetStartId(); s != "" {
			referenced[s] = true
		}
	}
	for _, t := range flowTransitions(d, flows) {
		referenced[t.GetFromId()] = true
		referenced[t.GetToId()] = true
	}
	var screens []*Screen
	seen := map[string]bool{}
	for _, p := range d.GetPages() {
		for _, n := range core.ChildrenOf(d, p.GetId()) {
			if !n.GetVisible() || seen[n.GetId()] {
				continue
			}
			_, isFrame := n.GetShape().(*opendesignerv1.Node_Frame)
			if !(isFrame && !masters[n.GetId()]) && !referenced[n.GetId()] {
				continue
			}
			seen[n.GetId()] = true
			screens = append(screens, &Screen{NodeID: n.GetId(), Width: n.GetWidth(), Height: n.GetHeight()})
		}
	}
	// No screens (top-level frames)? Typical case: an imported, animated SVG icon
	// or illustration. Then every visible top-level element becomes a "component"
	// exported as a page of its own, sized to its content.
	if len(screens) == 0 {
		for _, p := range d.GetPages() {
			for _, n := range core.ChildrenOf(d, p.GetId()) {
				if !n.GetVisible() || seen[n.GetId()] || masters[n.GetId()] {
					continue
				}
				w, h := n.GetWidth(), n.GetHeight()
				if w <= 0 || h <= 0 {
					w, h = contentSize(d, n.GetId())
				}
				if w <= 0 || h <= 0 {
					continue
				}
				seen[n.GetId()] = true
				screens = append(screens, &Screen{NodeID: n.GetId(), Width: w, Height: h})
			}
		}
		if len(screens) > 0 {
			*warnings = append(*warnings, "the document has no top-level frames: top-level elements are exported as screens (one per element)")
		}
	}
	for id := range referenced {
		if !seen[id] {
			*warnings = append(*warnings, fmt.Sprintf("the flow references %q, which is not a visible top-level node: it is not an exported screen", nameOrID(d, id)))
		}
	}
	return screens
}

func nameOrID(d *opendesignerv1.Document, id string) string {
	if n := d.GetNodes()[id].GetName(); n != "" {
		return n
	}
	return id
}

var reservedNames = map[string]bool{
	"App": true, "Route": true, "Routes": true, "Navigate": true, "BrowserRouter": true,
	"StrictMode": true, "React": true, "ReactDOM": true, "Link": true,
}

// assignNames gives every screen a component name, slug, route and file, and
// writes the route into the meta of flow screens that lack one.
func assignNames(d *opendesignerv1.Document, screens []*Screen, opts Options) {
	compUsed, slugUsed, routeUsed := map[string]bool{}, map[string]bool{"index": true}, map[string]bool{}
	flows := selectedFlows(d, opts.FlowID)
	inFlow := map[string]bool{}
	startOf := ""
	for _, f := range flows {
		if s := d.GetFlows()[f].GetStartId(); s != "" {
			inFlow[s] = true
			if startOf == "" {
				startOf = s
			}
		}
	}
	for _, t := range flowTransitions(d, flows) {
		inFlow[t.GetFromId()] = true
		inFlow[t.GetToId()] = true
	}
	for _, s := range screens {
		n := d.GetNodes()[s.NodeID]
		base := n.GetMeta()[flow.MetaComponent]
		if base == "" {
			base = n.GetName()
		}
		name := pascal(base)
		if reservedNames[name] {
			name += "Screen"
		}
		s.Name = dedupe(compUsed, name, "")
		s.Slug = dedupe(slugUsed, slug(n.GetName()), "-")
		route := strings.TrimSpace(n.GetMeta()[flow.MetaRoute])
		if route == "" {
			route = "/" + s.Slug
		} else if !strings.HasPrefix(route, "/") {
			route = "/" + route
		}
		s.Route = route
		routeUsed[route] = true
		if inFlow[s.NodeID] && n.GetMeta()[flow.MetaRoute] == "" {
			if n.Meta == nil {
				n.Meta = map[string]string{}
			}
			n.Meta[flow.MetaRoute] = route
		}
		s.File = s.Slug + ".html"
	}
	// The entry point of the first flow with a start screen is
	// index.html (html) and the "/" route (react).
	if opts.Target == TargetHTML && startOf != "" {
		for _, s := range screens {
			if s.NodeID == startOf {
				s.File = "index.html"
			}
		}
	}
}

// wireFlows builds the IR of every screen and attaches the transitions to it.
func wireFlows(d *opendesignerv1.Document, screens []*Screen, opts Options, b *builder, warnings *[]string) {
	byNode := map[string]*Screen{}
	for _, s := range screens {
		byNode[s.NodeID] = s
	}
	trans := flowTransitions(d, selectedFlows(d, opts.FlowID))
	perScreen := map[string][]*opendesignerv1.Transition{}
	for _, t := range trans {
		if byNode[t.GetFromId()] == nil {
			continue
		}
		perScreen[t.GetFromId()] = append(perScreen[t.GetFromId()], t)
	}

	for _, s := range screens {
		node := d.GetNodes()[s.NodeID]
		b.triggers = map[string][]Trigger{}
		var nav, keys []Trigger
		for _, t := range perScreen[s.NodeID] {
			tr := Trigger{
				TransitionID: t.GetId(), FlowID: t.GetFlowId(), Label: t.GetLabel(), Kind: t.GetTrigger(),
				Guard: t.GetGuard(), Effect: t.GetEffect(), Dest: byNode[t.GetToId()],
			}
			if tr.Dest == nil && tr.Kind != "back" {
				*warnings = append(*warnings, fmt.Sprintf("transition %s: the destination %q is not an exported screen", t.GetId(), nameOrID(d, t.GetToId())))
			}
			switch tr.Kind {
			case "key":
				if strings.TrimSpace(tr.Label) == "" {
					*warnings = append(*warnings, fmt.Sprintf("transition %s: key trigger without a label (the key to press), not wired", t.GetId()))
					continue
				}
				keys = append(keys, tr)
			case "auto":
				nav = append(nav, tr)
			default:
				el := t.GetElementId()
				inside := el != "" && (el == s.NodeID || core.IsAncestorOf(d, s.NodeID, el))
				if inside && len(b.triggers[el]) == 0 && tr.Kind != "back" {
					b.triggers[el] = append(b.triggers[el], tr)
				} else {
					nav = append(nav, tr)
				}
			}
		}
		s.Root = b.buildScreen(node)
		if s.Root == nil {
			// Screen without elements (frame with a zero side and no children): it stays an empty container.
			s.Root = &Element{Tag: "div", NodeID: node.GetId(), NodeName: node.GetName()}
			s.Root.Attrs = []Attr{{"data-node-id", node.GetId()}}
		}
		// A trigger whose element was not emitted (hidden node, degenerate shape)
		// cannot fire anything: fall back to the hidden button.
		attached := map[string]bool{}
		s.Root.walk(func(e *Element) {
			for _, tr := range e.Triggers {
				attached[tr.TransitionID] = true
			}
		})
		for _, trs := range b.triggers {
			for _, tr := range trs {
				if !attached[tr.TransitionID] {
					nav = append(nav, tr)
				}
			}
		}
		sort.SliceStable(nav, func(i, j int) bool { return nav[i].TransitionID < nav[j].TransitionID })
		s.Root.NavTriggers = nav
		s.Root.KeyTriggers = keys
	}
}

// contentSize: the size covering the descendants of `id` in the node's local
// space (children live in their parent's coordinates). Used for a group, which
// has no size of its own. It ignores rotations: it is an estimate for the container.
func contentSize(d *opendesignerv1.Document, id string) (float64, float64) {
	var w, h float64
	var walk func(parent string, ox, oy float64, depth int)
	walk = func(parent string, ox, oy float64, depth int) {
		if depth > 64 {
			return
		}
		for _, c := range core.ChildrenOf(d, parent) {
			if !c.GetVisible() {
				continue
			}
			if r := ox + c.GetX() + c.GetWidth(); r > w {
				w = r
			}
			if b := oy + c.GetY() + c.GetHeight(); b > h {
				h = b
			}
			walk(c.GetId(), ox+c.GetX(), oy+c.GetY(), depth+1)
		}
	}
	walk(id, 0, 0, 0)
	return w, h
}
