// File generated by opendesigner (opendesigner flow tests): DO NOT edit by hand,
// regenerate from the flow graph.
// Document: Shop (shop)
// Flows: all
import { expect, test } from '@playwright/test';

test.describe("Flow: Purchase", () => {
  test("path 1: Login → Home → Detail → Home (cycle)", async ({ page }) => {
    await page.goto("/login");

    // flow:t1
    // Login -> Home
    // guard: valid credentials
    // effect: active session
    await page.getByTestId("login-submit").click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/home/?(?:[?#].*)?$"));

    // flow:t2
    // Home -> Detail
    await page.getByText("Wireless headphones").click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/detail/?(?:[?#].*)?$"));

    // flow:t4
    // Detail -> Home
    await page.getByRole('button', { name: "Back" }).click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/home/?(?:[?#].*)?$"));
  });
  test("path 2: Login → Home → Login (cycle)", async ({ page }) => {
    await page.goto("/login");

    // flow:t1
    // Login -> Home
    // guard: valid credentials
    // effect: active session
    await page.getByTestId("login-submit").click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/home/?(?:[?#].*)?$"));

    // flow:t3
    // Home -> Login
    await page.getByRole('button', { name: "Sign out" }).click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/login/?(?:[?#].*)?$"));
  });
});
