// File generated by opendesigner (opendesigner flow tests): DO NOT edit by hand,
// regenerate from the flow graph.
// Document: Shop (doc1)
// Flow: Purchase (checkout)
import { expect, test } from '@playwright/test';

test.describe("Flow: Purchase", () => {
  test("path 1: Home → Cart → Home (cycle)", async ({ page }) => {
    await page.goto("/");

    // flow:t-key
    // Home -> Cart
    await page.keyboard.press("Enter");
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/cart/[^/]+/?(?:[?#].*)?$"));

    // flow:t-back
    // Cart -> Home
    // effect: empties the cart
    await page.goBack();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/?(?:[?#].*)?$"));
  });
  test("path 2: Home → Cart → Payment → Thanks", async ({ page }) => {
    await page.goto("/");

    // flow:t-key
    // Home -> Cart
    await page.keyboard.press("Enter");
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/cart/[^/]+/?(?:[?#].*)?$"));

    // flow:t-pay
    // Cart -> Payment
    // guard: cart not empty
    // effect: order created
    await page.getByRole('button', { name: "Pay" }).click();

    // flow:t-done
    // Payment -> Thanks
    // trigger auto: no action, the transition fires by itself
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/thanks/?(?:[?#].*)?$"));
  });
  test("path 3: Home → Login → Cart → Home (cycle)", async ({ page }) => {
    await page.goto("/");

    // flow:t-login
    // Home -> Login
    await page.getByTestId("go-login").click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/login/?(?:[?#].*)?$"));

    // flow:t-cart
    // Login -> Cart
    await page.getByText("Go to cart").click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/cart/[^/]+/?(?:[?#].*)?$"));

    // flow:t-back
    // Cart -> Home
    // effect: empties the cart
    await page.goBack();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/?(?:[?#].*)?$"));
  });
  test("path 4: Home → Login → Cart → Payment → Thanks", async ({ page }) => {
    await page.goto("/");

    // flow:t-login
    // Home -> Login
    await page.getByTestId("go-login").click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/login/?(?:[?#].*)?$"));

    // flow:t-cart
    // Login -> Cart
    await page.getByText("Go to cart").click();
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/cart/[^/]+/?(?:[?#].*)?$"));

    // flow:t-pay
    // Cart -> Payment
    // guard: cart not empty
    // effect: order created
    await page.getByRole('button', { name: "Pay" }).click();

    // flow:t-done
    // Payment -> Thanks
    // trigger auto: no action, the transition fires by itself
    await expect(page).toHaveURL(new RegExp("^[a-z]+://[^/]+/thanks/?(?:[?#].*)?$"));
  });
});
