package flow

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"

	opendesignerv1 "github.com/bernardoforcillo/opendesigner/gen/opendesigner/v1"
)

// GeneratedMarker appears in the header of generated files: Coverage uses it
// to avoid counting a generated test (which cites routes and components) as
// an implementation of the screens.
const GeneratedMarker = "File generated by opendesigner"

// PlaywrightOptions regola la generazione.
type PlaywrightOptions struct {
	// BaseURL, if not empty, precedes the routes in `page.goto`. Normally it stays
	// empty and `use.baseURL` is configured in playwright.config.
	BaseURL string
}

// PlaywrightTests generates a TypeScript file for `@playwright/test` with one
// `test()` per flow path (flowID "" = all). Every transition is
// preceded by `// flow:<id>`, the annotation Coverage looks for in the repository
// to say the edge is tested.
//
// The trigger's locator is resolved in this order: the element's `test.id` ->
// `getByTestId`; `test.text` -> `getByText`; otherwise the transition's
// label -> `getByRole('button', { name })` (`getByText` if the trigger is not
// click/submit). If there is no way to find the element, or the start screen's
// `code.route` is missing, the test emits a `// TODO` and `test.fixme`.
// After every step, if the destination has `code.route`, the URL is asserted.
func PlaywrightTests(doc *opendesignerv1.Document, flowID string, opts PlaywrightOptions) (string, error) {
	ids := flowIDs(doc, flowID)
	if len(ids) == 0 {
		if flowID != "" {
			return "", fmt.Errorf("flow %q not found in the document", flowID)
		}
		return "", errors.New("the document has no flows")
	}

	var body strings.Builder
	usesExpect := false
	for _, id := range ids {
		g := buildGraph(doc, id)
		rep := analyzeFlow(g, id)
		writeFlowTests(&body, g, rep, opts, &usesExpect)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// %s (opendesigner flow tests): DO NOT edit by hand,\n", GeneratedMarker)
	b.WriteString("// regenerate from the flow graph.\n")
	fmt.Fprintf(&b, "// Document: %s (%s)\n", oneLine(doc.GetName()), doc.GetId())
	if flowID != "" {
		fmt.Fprintf(&b, "// Flow: %s (%s)\n", oneLine(g0name(doc, flowID)), flowID)
	} else {
		b.WriteString("// Flows: all\n")
	}
	if usesExpect {
		b.WriteString("import { expect, test } from '@playwright/test';\n")
	} else {
		b.WriteString("import { test } from '@playwright/test';\n")
	}
	b.WriteString(body.String())
	return b.String(), nil
}

func g0name(doc *opendesignerv1.Document, flowID string) string {
	if n := doc.GetFlows()[flowID].GetName(); n != "" {
		return n
	}
	return flowID
}

func writeFlowTests(b *strings.Builder, g *graph, rep *opendesignerv1.FlowReport, opts PlaywrightOptions, usesExpect *bool) {
	b.WriteString("\n")
	fmt.Fprintf(b, "test.describe(%s, () => {\n", tsString("Flow: "+oneLine(g0name(g.doc, g.flow.GetId()))))
	if len(rep.GetPaths()) == 0 {
		b.WriteString("  // No paths: the start screen or the transitions are missing.\n")
	}
	byID := map[string]*opendesignerv1.Transition{}
	for _, t := range g.trans {
		byID[t.GetId()] = t
	}
	for i, p := range rep.GetPaths() {
		names := make([]string, len(p.GetNodeIds()))
		for j, id := range p.GetNodeIds() {
			names[j] = nodeName(g.doc, id)
		}
		title := fmt.Sprintf("path %d: %s", i+1, strings.Join(names, " → "))
		if p.GetLoops() {
			title += " (cycle)"
		}
		writeTest(b, g, byID, p, oneLine(title), opts, usesExpect)
	}
	b.WriteString("});\n")
}

func writeTest(b *strings.Builder, g *graph, byID map[string]*opendesignerv1.Transition, p *opendesignerv1.FlowPath, title string, opts PlaywrightOptions, usesExpect *bool) {
	var steps strings.Builder
	var todos []string
	start := p.GetNodeIds()[0]
	if route := nodeMeta(g.doc, start, MetaRoute); route != "" {
		fmt.Fprintf(&steps, "    await page.goto(%s);\n", tsString(opts.BaseURL+route))
	} else {
		msg := fmt.Sprintf("code.route is missing on %q", oneLine(nodeName(g.doc, start)))
		fmt.Fprintf(&steps, "    // TODO: %s\n", msg)
		todos = append(todos, msg)
	}

	for i, tid := range p.GetTransitionIds() {
		t := byID[tid]
		to := p.GetNodeIds()[i+1]
		fmt.Fprintf(&steps, "\n    // flow:%s\n", t.GetId())
		fmt.Fprintf(&steps, "    // %s -> %s\n", oneLine(nodeName(g.doc, t.GetFromId())), oneLine(nodeName(g.doc, t.GetToId())))
		if t.GetGuard() != "" {
			fmt.Fprintf(&steps, "    // guard: %s\n", oneLine(t.GetGuard()))
		}
		if t.GetEffect() != "" {
			fmt.Fprintf(&steps, "    // effect: %s\n", oneLine(t.GetEffect()))
		}
		if msg := writeAction(&steps, g.doc, t, usesExpect); msg != "" {
			todos = append(todos, msg)
		}
		if route := nodeMeta(g.doc, to, MetaRoute); route != "" {
			*usesExpect = true
			fmt.Fprintf(&steps, "    await expect(page).toHaveURL(new RegExp(%s));\n", tsString(routePattern(route)))
		}
	}

	fmt.Fprintf(b, "  test(%s, async ({ page }) => {\n", tsString(title))
	if len(todos) > 0 {
		fmt.Fprintf(b, "    test.fixme(true, %s);\n", tsString(strings.Join(todos, "; ")))
	}
	b.WriteString(steps.String())
	b.WriteString("  });\n")
}

// writeAction emits the trigger's action; if it does not know how to find the element
// it emits a TODO and returns the reason (the test becomes fixme).
func writeAction(b *strings.Builder, doc *opendesignerv1.Document, t *opendesignerv1.Transition, usesExpect *bool) string {
	trig := t.GetTrigger()
	switch trig {
	case "auto":
		b.WriteString("    // trigger auto: no action, the transition fires by itself\n")
		return ""
	case "back":
		b.WriteString("    await page.goBack();\n")
		return ""
	case "key":
		if t.GetLabel() == "" {
			msg := fmt.Sprintf("transition %s: trigger key without a label (the key to press)", t.GetId())
			fmt.Fprintf(b, "    // TODO: %s\n", msg)
			return msg
		}
		fmt.Fprintf(b, "    await page.keyboard.press(%s);\n", tsString(t.GetLabel()))
		return ""
	}

	clickLike := trig == "" || trig == "click" || trig == "submit"
	loc := ""
	switch {
	case t.GetElementId() != "" && nodeMeta(doc, t.GetElementId(), MetaTestID) != "":
		loc = fmt.Sprintf("page.getByTestId(%s)", tsString(nodeMeta(doc, t.GetElementId(), MetaTestID)))
	case t.GetElementId() != "" && nodeMeta(doc, t.GetElementId(), MetaTestText) != "":
		loc = fmt.Sprintf("page.getByText(%s)", tsString(nodeMeta(doc, t.GetElementId(), MetaTestText)))
	case t.GetLabel() != "" && clickLike:
		loc = fmt.Sprintf("page.getByRole('button', { name: %s })", tsString(t.GetLabel()))
	case t.GetLabel() != "":
		loc = fmt.Sprintf("page.getByText(%s)", tsString(t.GetLabel()))
	}
	if loc == "" {
		msg := fmt.Sprintf("transition %s: no test.id/test.text on the element and no label to find the trigger", t.GetId())
		fmt.Fprintf(b, "    // TODO: %s\n", msg)
		return msg
	}
	if clickLike {
		fmt.Fprintf(b, "    await %s.click();\n", loc)
		return ""
	}
	// Free-text trigger (hover, long press...): it cannot be simulated, but at least
	// it is verified that the element is there.
	*usesExpect = true
	msg := fmt.Sprintf("transition %s: trigger %q must be simulated by hand", t.GetId(), trig)
	fmt.Fprintf(b, "    // TODO: %s\n", msg)
	fmt.Fprintf(b, "    await expect(%s).toBeVisible();\n", loc)
	return msg
}

var jsRegexSpecial = regexp.MustCompile(`[.*+?^${}()|\[\]\\/]`)

var paramSegment = regexp.MustCompile(`^(?::[A-Za-z_][\w-]*|\[[^\]]+\])$`)

// routePattern builds the source of a RegExp that recognizes the route's
// URL: anchored to scheme+host, tolerates a trailing slash, query and hash. Parametric
// segments (`:id`, `[id]`) become `[^/]+`; the rest is escaped.
func routePattern(route string) string {
	route = strings.TrimRight(route, "/")
	if route != "" && !strings.HasPrefix(route, "/") {
		route = "/" + route
	}
	var sb strings.Builder
	sb.WriteString(`^[a-z]+://[^/]+`)
	for _, seg := range strings.Split(strings.TrimPrefix(route, "/"), "/") {
		if seg == "" {
			continue
		}
		sb.WriteString("/")
		if paramSegment.MatchString(seg) {
			sb.WriteString(`[^/]+`)
		} else {
			sb.WriteString(jsRegexSpecial.ReplaceAllString(seg, `\$0`))
		}
	}
	sb.WriteString(`/?(?:[?#].*)?$`)
	return sb.String()
}

// tsString quotes a string as a valid TypeScript literal (JSON escaping), without
// the HTML escaping json.Marshal would apply by default.
func tsString(s string) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(s)
	return strings.TrimRight(buf.String(), "\n")
}
